### PR TITLE
Lorena cart pop up 13

### PR DESCRIPTION
**Pull request by LorenaCapraru**
I created the pop-up. 
- [x] Desktop Design 
- [x] Mobile Design 
- [x] Delete element in the basket feature
- [x] adjusts the total according to the number of elements
- [x] fixed the heading responsiveness problem

### CODE REVIEW

**Comment by momahboobian** [comment]
Great job @LorenaCapraru. well done.
You migh be able to twick the stylesheet to be a bit perfect. Also if you have time you can make the clicking a bit natural.


https://github.com/LorenaCapraru/g1-e-commerce-app/assets/17272675/70705977-8e18-4f8b-a567-ab6d0ea55406

**Comment by momahboobian** [comment]
Great job @LorenaCapraru. well done.
You migh be able to twick the stylesheet to be a bit perfect. Also if you have time you can make the clicking a bit natural.


https://github.com/LorenaCapraru/g1-e-commerce-app/assets/17272675/70705977-8e18-4f8b-a567-ab6d0ea55406

**Review by momahboobian — CHANGES_REQUESTED** [review]
Great job @LorenaCapraru. well done.
You migh be able to twick the stylesheet to be a bit perfect. Also if you have time you can make the clicking a bit natural.


https://github.com/LorenaCapraru/g1-e-commerce-app/assets/17272675/70705977-8e18-4f8b-a567-ab6d0ea55406

**Comment by LorenaCapraru** [comment]
Thank you for feedback, @momahboobian , I made the adjustments. Please, check.

**Comment by momahboobian** [comment]
> 

Thanks @LorenaCapraru 😊

I meant you could add transition in your css to have a slide delay for displaying the box when click on the card. and I should have explained it better. 🫣😅
One more update if you have time to mage the box position absolut this will help when you check the website on small screen the box wouldnt go over the card and profile image. (you can watched the video on my previous review)

**Review by momahboobian — APPROVED** [review]
well done 🤌🏼

**Pull request merged**
